---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

 

```{r}
library(readxl)
```

```{r}
library(readr)
WS <- read_csv("D://K-MEANS/WS.csv")
View(WS)
summary(WS)
```


```{r}
WS.new <- WS[, 1:4]
WS.class <- WS[, "Grocery"]
set.seed(1356)
result <- kmeans(WS.new, 3)
```


```{r}
par(mfrow=c(2,2), mar=c(5,4,2,2))
plot(WS.new[, c(1,2)], col=result$cluster)
plot(WS.new[, c(1,2)], col=WS.class)
```


```{r}
plot(WS.new[, c(3,4)], col=result$cluster)
plot(WS.new[, c(3,4)], col=WS.class)
```

## Warning in plot.xy(xy, type, ...): supplied color is neither numeric nor
## character

```{r}
result$tot.withinss
```


```{r}
attributes(result)$names
```

```{r}
WS.new$cluster <- factor(result$cluster)
centers <- as.data.frame(result$centers)
library(ggplot2)
```

```{r}
ggplot() + 
  geom_point(data=WS.new, aes(x=Channel, y=Region,color=cluster))  +
  geom_point(data=centers, aes(x=Channel, y=Region, color="Center"), 
             size=52, alpha=.3, show.legend = FALSE)
```


```{r}
set.seed (2)
Region <- matrix (rnorm (50*2) , ncol =2)
Region[1:25 ,1] <- Region[1:25 ,1] + 3
Region[1:25 ,2]<- Region[1:25 ,2] - 4
plot(WS)
```

```{r}
WS <- kmeans(Region, 2)
plot(Region, col = (WS$cluster +1))
```








